#include "test.h"


lexer_test_rules::lexer_test_rules(const parse::lexer& tok)
{
    namespace qi = boost::spirit::qi;
    namespace phoenix = boost::phoenix;
    using qi::_1;
    using phoenix::val;

    lexer
        =   * (
                   tok.inline_comment [ std::cout << val("<INLINE COMMENT>\n") ]
                |  tok.end_of_line_comment [ std::cout << val("<END OF LINE COMMENT>\n") ]

                |  tok.bool_ [ std::cout << _1 << " BOOL\n" ]
                |  tok.int_ [ std::cout << _1 << " INT\n" ]
                |  tok.double_ [ std::cout << _1 << " DOUBLE\n" ]
                |  tok.string [ std::cout << _1 << " STRING\n" ]

                |  tok.planet_size_enum [ std::cout << _1 << " PLANET_SIZE\n" ]
                |  tok.planet_type_enum [ std::cout << _1 << " PLANET_TYPE\n" ]
                |  tok.planet_environment_enum [ std::cout << _1 << " PLANET_ENVIRONMENT\n" ]
                |  tok.universe_object_type_enum [ std::cout << _1 << " UNIVERSE_OBJECT_TYPE\n" ]
                |  tok.star_type_enum [ std::cout << _1 << " STAR_TYPE\n" ]
                |  tok.empire_affiliation_type_enum [ std::cout << _1 << " EMPIRE_AFFILIATION_TYPE\n" ]
                |  tok.unlockable_item_type_enum [ std::cout << _1 << " UNLOCKABLE_ITEM_TYPE\n" ]
                |  tok.tech_type_enum [ std::cout << _1 << " TECH_TYPE\n" ]
                |  tok.combat_fighter_type_enum [ std::cout << _1 << " COMBAT_FIGHTER_TYPE\n" ]
                |  tok.ship_part_class_enum [ std::cout << _1 << " SHIP_PART_CLASS\n" ]
                |  tok.ship_slot_type_enum [ std::cout << _1 << " SHIP_SLOT_TYPE\n" ]
                |  tok.capture_result_enum [ std::cout << _1 << " CAPTURE_RESULT\n" ]
                |  tok.statistic_type_enum [ std::cout << _1 << " STATISTIC TYPE\n" ]

                |  tok.activation [ std::cout << _1 << "\n" ]
                |  tok.added_before [ std::cout << _1 << "\n" ]
                |  tok.added_since [ std::cout << _1 << "\n" ]
                |  tok.affiliation [ std::cout << _1 << "\n" ]
                |  tok.age [ std::cout << _1 << "\n" ]
                |  tok.alignment [ std::cout << _1 << "\n" ]
                |  tok.all [ std::cout << _1 << "\n" ]
                |  tok.and_ [ std::cout << _1 << "\n" ]
                |  tok.anti_fighter_damage [ std::cout << _1 << "\n" ]
                |  tok.anti_ship_damage [ std::cout << _1 << "\n" ]
                |  tok.armed [ std::cout << _1 << "\n" ]
                |  tok.asteroids [ std::cout << _1 << "\n" ]
                |  tok.battle_speed [ std::cout << _1 << "\n" ]
                |  tok.build_cost [ std::cout << _1 << "\n" ]
                |  tok.building [ std::cout << _1 << "\n" ]
                |  tok.building_type [ std::cout << _1 << "\n" ]
                |  tok.build_time [ std::cout << _1 << "\n" ]
                |  tok.capacity [ std::cout << _1 << "\n" ]
                |  tok.capital [ std::cout << _1 << "\n" ]
                |  tok.capture_result [ std::cout << _1 << "\n" ]
                |  tok.category [ std::cout << _1 << "\n" ]
                |  tok.class_ [ std::cout << _1 << "\n" ]
                |  tok.colour [ std::cout << _1 << "\n" ]
                |  tok.condition [ std::cout << _1 << "\n" ]
                |  tok.construction [ std::cout << _1 << "\n" ]
                |  tok.contained_by [ std::cout << _1 << "\n" ]
                |  tok.contains [ std::cout << _1 << "\n" ]
                |  tok.created_on_turn [ std::cout << _1 << "\n" ]
                |  tok.creation_turn [ std::cout << _1 << "\n" ]
                |  tok.damage [ std::cout << _1 << "\n" ]
                |  tok.defense [ std::cout << _1 << "\n" ]
                |  tok.description [ std::cout << _1 << "\n" ]
                |  tok.design_has_hull [ std::cout << _1 << "\n" ]
                |  tok.design_has_part_class [ std::cout << _1 << "\n" ]
                |  tok.design_has_part [ std::cout << _1 << "\n" ]
                |  tok.design_id [ std::cout << _1 << "\n" ]
                |  tok.design [ std::cout << _1 << "\n" ]
                |  tok.detection [ std::cout << _1 << "\n" ]
                |  tok.distance [ std::cout << _1 << "\n" ]
                |  tok.distance_to_source [ std::cout << _1 << "\n" ]
                |  tok.effects_groups [ std::cout << _1 << "\n" ]
                |  tok.effects_group [ std::cout << _1 << "\n" ]
                |  tok.effects [ std::cout << _1 << "\n" ]
                |  tok.empire [ std::cout << _1 << "\n" ]
                |  tok.environments [ std::cout << _1 << "\n" ]
                |  tok.environment [ std::cout << _1 << "\n" ]
                |  tok.explored_by_empire [ std::cout << _1 << "\n" ]
                |  tok.farming [ std::cout << _1 << "\n" ]
                |  tok.fighter_type [ std::cout << _1 << "\n" ]
                |  tok.fighter_weapon_range [ std::cout << _1 << "\n" ]
                |  tok.final_destination_id [ std::cout << _1 << "\n" ]
                |  tok.fleet_id [ std::cout << _1 << "\n" ]
                |  tok.fleet [ std::cout << _1 << "\n" ]
                |  tok.fleet_supplyable_by_empire [ std::cout << _1 << "\n" ]
                |  tok.foci [ std::cout << _1 << "\n" ]
                |  tok.focus [ std::cout << _1 << "\n" ]
                |  tok.food_consumption [ std::cout << _1 << "\n" ]
                |  tok.food_stockpile [ std::cout << _1 << "\n" ]
                |  tok.fuel [ std::cout << _1 << "\n" ]
                |  tok.gas_giant [ std::cout << _1 << "\n" ]
                |  tok.graphic [ std::cout << _1 << "\n" ]
                |  tok.has_special [ std::cout << _1 << "\n" ]
                |  tok.health [ std::cout << _1 << "\n" ]
                |  tok.high [ std::cout << _1 << "\n" ]
                |  tok.homeworld [ std::cout << _1 << "\n" ]
                |  tok.hull [ std::cout << _1 << "\n" ]
                |  tok.id [ std::cout << _1 << "\n" ]
                |  tok.industry [ std::cout << _1 << "\n" ]
                |  tok.in_system [ std::cout << _1 << "\n" ]
                |  tok.item [ std::cout << _1 << "\n" ]
                |  tok.jumps [ std::cout << _1 << "\n" ]
                |  tok.launch_rate [ std::cout << _1 << "\n" ]
                |  tok.local_candidate [ std::cout << _1 << "\n" ]
                |  tok.location [ std::cout << _1 << "\n" ]
                |  tok.lookup_strings [ std::cout << _1 << "\n" ]
                |  tok.low [ std::cout << _1 << "\n" ]
                |  tok.max_defense [ std::cout << _1 << "\n" ]
                |  tok.max_fuel [ std::cout << _1 << "\n" ]
                |  tok.maximum_number_of [ std::cout << _1 << "\n" ]
                |  tok.max_shield [ std::cout << _1 << "\n" ]
                |  tok.max_structure [ std::cout << _1 << "\n" ]
                |  tok.max_troops [ std::cout << _1 << "\n" ]
                |  tok.mineral_stockpile [ std::cout << _1 << "\n" ]
                |  tok.minimum_number_of [ std::cout << _1 << "\n" ]
                |  tok.mining [ std::cout << _1 << "\n" ]
                |  tok.model [ std::cout << _1 << "\n" ]
                |  tok.mode_number_of [ std::cout << _1 << "\n" ]
                |  tok.monster_fleet [ std::cout << _1 << "\n" ]
                |  tok.monster [ std::cout << _1 << "\n" ]
                |  tok.mountable_slot_types [ std::cout << _1 << "\n" ]
                |  tok.name [ std::cout << _1 << "\n" ]
                |  tok.next_better_planet_type [ std::cout << _1 << "\n" ]
                |  tok.next_system_id [ std::cout << _1 << "\n" ]
                |  tok.not_ [ std::cout << _1 << "\n" ]
                |  tok.number_of [ std::cout << _1 << "\n" ]
                |  tok.number [ std::cout << _1 << "\n" ]
                |  tok.num_ships [ std::cout << _1 << "\n" ]
                |  tok.object [ std::cout << _1 << "\n" ]
                |  tok.object_type [ std::cout << _1 << "\n" ]
                |  tok.or_ [ std::cout << _1 << "\n" ]
                |  tok.ownedby [ std::cout << _1 << "\n" ]
                |  tok.owner_food_stockpile [ std::cout << _1 << "\n" ]
                |  tok.owner_has_tech [ std::cout << _1 << "\n" ]
                |  tok.owner_mineral_stockpile [ std::cout << _1 << "\n" ]
                |  tok.owner [ std::cout << _1 << "\n" ]
                |  tok.owner_trade_stockpile [ std::cout << _1 << "\n" ]
                |  tok.parts [ std::cout << _1 << "\n" ]
                |  tok.part [ std::cout << _1 << "\n" ]
                |  tok.planetbound [ std::cout << _1 << "\n" ]
                |  tok.planet_environment [ std::cout << _1 << "\n" ]
                |  tok.planet_id [ std::cout << _1 << "\n" ]
                |  tok.planet_size [ std::cout << _1 << "\n" ]
                |  tok.planet [ std::cout << _1 << "\n" ]
                |  tok.planet_type [ std::cout << _1 << "\n" ]
                |  tok.population [ std::cout << _1 << "\n" ]
                |  tok.position [ std::cout << _1 << "\n" ]
                |  tok.prerequisites [ std::cout << _1 << "\n" ]
                |  tok.previous_system_id [ std::cout << _1 << "\n" ]
                |  tok.probability [ std::cout << _1 << "\n" ]
                |  tok.produced_by_empireid [ std::cout << _1 << "\n" ]
                |  tok.produced_by_empire [ std::cout << _1 << "\n" ]
                |  tok.producible [ std::cout << _1 << "\n" ]
                |  tok.property [ std::cout << _1 << "\n" ]
                |  tok.random [ std::cout << _1 << "\n" ]
                |  tok.range [ std::cout << _1 << "\n" ]
                |  tok.researchable [ std::cout << _1 << "\n" ]
                |  tok.research_cost [ std::cout << _1 << "\n" ]
                |  tok.research [ std::cout << _1 << "\n" ]
                |  tok.research_turns [ std::cout << _1 << "\n" ]
                |  tok.resource_supply_connected_by_empire [ std::cout << _1 << "\n" ]
                |  tok.rof [ std::cout << _1 << "\n" ]
                |  tok.root_candidate [ std::cout << _1 << "\n" ]
                |  tok.scope [ std::cout << _1 << "\n" ]
                |  tok.shield [ std::cout << _1 << "\n" ]
                |  tok.shipdesign [ std::cout << _1 << "\n" ]
                |  tok.ships [ std::cout << _1 << "\n" ]
                |  tok.short_description [ std::cout << _1 << "\n" ]
                |  tok.size [ std::cout << _1 << "\n" ]
                |  tok.slots [ std::cout << _1 << "\n" ]
                |  tok.slot [ std::cout << _1 << "\n" ]
                |  tok.sortby [ std::cout << _1 << "\n" ]
                |  tok.source [ std::cout << _1 << "\n" ]
                |  tok.spacebound [ std::cout << _1 << "\n" ]
                |  tok.spawn_limit [ std::cout << _1 << "\n" ]
                |  tok.spawn_rate [ std::cout << _1 << "\n" ]
                |  tok.special [ std::cout << _1 << "\n" ]
                |  tok.species [ std::cout << _1 << "\n" ]
                |  tok.speed [ std::cout << _1 << "\n" ]
                |  tok.stacking_group [ std::cout << _1 << "\n" ]
                |  tok.starlane_speed [ std::cout << _1 << "\n" ]
                |  tok.star [ std::cout << _1 << "\n" ]
                |  tok.star_type [ std::cout << _1 << "\n" ]
                |  tok.stationary [ std::cout << _1 << "\n" ]
                |  tok.stealth [ std::cout << _1 << "\n" ]
                |  tok.structure [ std::cout << _1 << "\n" ]
                |  tok.supply [ std::cout << _1 << "\n" ]
                |  tok.system_id [ std::cout << _1 << "\n" ]
                |  tok.system [ std::cout << _1 << "\n" ]
                |  tok.target_construction [ std::cout << _1 << "\n" ]
                |  tok.target_farming [ std::cout << _1 << "\n" ]
                |  tok.target_health [ std::cout << _1 << "\n" ]
                |  tok.target_industry [ std::cout << _1 << "\n" ]
                |  tok.target_mining [ std::cout << _1 << "\n" ]
                |  tok.target_population [ std::cout << _1 << "\n" ]
                |  tok.target_research [ std::cout << _1 << "\n" ]
                |  tok.target [ std::cout << _1 << "\n" ]
                |  tok.target_trade [ std::cout << _1 << "\n" ]
                |  tok.tech [ std::cout << _1 << "\n" ]
                |  tok.tech_type [ std::cout << _1 << "\n" ]
                |  tok.trade [ std::cout << _1 << "\n" ]
                |  tok.trade_stockpile [ std::cout << _1 << "\n" ]
                |  tok.troops [ std::cout << _1 << "\n" ]
                |  tok.turn [ std::cout << _1 << "\n" ]
                |  tok.type [ std::cout << _1 << "\n" ]
                |  tok.unlock [ std::cout << _1 << "\n" ]
                |  tok.value [ std::cout << _1 << "\n" ]
                |  tok.visible_to_empire [ std::cout << _1 << "\n" ]
                |  tok.within_distance [ std::cout << _1 << "\n" ]
                |  tok.within_starlane_jumps [ std::cout << _1 << "\n" ]

                |  '='
                |  '+'
                |  '-'
                |  '*'
                |  '/'
                |  '.'
                |  ','
                |  '('
                |  ')'
                |  '['
                |  ']'
              )
        ;

#define NAME(x)
// x.name(#x); debug(x)
    NAME(lexer);
#undef NAME
}
